services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - CONTENTFUL_SPACE_ID=${CONTENTFUL_SPACE_ID:-}
      - CONTENTFUL_ACCESS_TOKEN=${CONTENTFUL_ACCESS_TOKEN:-}
    restart: unless-stopped